import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

import { ThemeProvider } from '@/lib/providers/next-theme-provider'

import './globals.css'
// import db from '@/lib/supabase/db'

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // console.log(db)
  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
